@import gg.jte.Content

@param Content content

<!doctype html>
<html lang="pl-PL">
<head data-theme="light">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Lexi">
    <link rel="stylesheet" href="/css/style.css">
    <script src="/js/moxi@0.1.1.js"></script>
    <script src="/js/fixi@0.9.4.js"></script>
    <script src="/js/paxi@0.0.1.js"></script>
    <script src="/js/rexi@0.0.1.js"></script>
    <script src="/js/ssexi@0.0.1.js"></script>
    <title>Lexi</title>
</head>
<body>
    <main class="container">
        ${content}
    </main>
</body>
</html>
